version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  nextjs:
    build: ./nextjs
    ports:
      - "3001:3000"
    depends_on:
      - backend
